import AppKit
import Foundation
import UniformTypeIdentifiers

/// Watches the system pasteboard and files whatever lands on it into `ClipboardStore`.
///
/// macOS has no "pasteboard changed" notification, so this polls `changeCount` — a single
/// integer compare a few times a second, which is what every clipboard manager does.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// Password managers and the like. Copying from these is deliberately never recorded.
    private static let ignoredApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword-osx", "com.agilebits.onepassword7",
        "com.bitwarden.desktop", "com.lastpass.LastPass", "com.apple.keychainaccess",
        "com.apple.Passwords", "org.keepassxc.keepassxc", "com.dashlane.dashlanephonefinal",
        "in.sinew.Enpass-Desktop", "com.nordsec.nordpass",
    ]

    /// The de-facto standard pasteboard types password managers (and well-behaved apps) put
    /// on anything that shouldn't be remembered — see nspasteboard.org.
    private static let secretTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after Papla itself writes to the pasteboard, so that write isn't mistaken
    /// for the user copying something — otherwise the old clipboard, restored after a paste,
    /// would keep jumping back to the top of the history.
    func adopt() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    // MARK: - Reading

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        capture(from: pasteboard)
    }

    private func capture(from pasteboard: NSPasteboard) {
        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.secretTypes) else { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bundleID = front?.bundleIdentifier, Self.ignoredApps.contains(bundleID) { return }

        let settings = Settings.shared
        var item = ClipboardItem(
            date: Date(), kind: .text,
            appName: front?.localizedName, bundleID: front?.bundleIdentifier
        )

        // Files first: copying a file in Finder also puts its name on the pasteboard as text.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            item.filePaths = urls.map(\.path)
            // A copied picture *file* is an image as far as anyone browsing the history is
            // concerned — it belongs under "Obrazy", with a real thumbnail. That's independent
            // of "Zapamiętuj też obrazy": that setting is about keeping a PNG *copy* of pixels
            // on disk, and a file already lives on disk.
            if urls.allSatisfy(Self.isImageFile) {
                item.kind = .image
                item.imageDigest = "files:" + urls.map(\.path).joined(separator: "\n")
                if let first = urls.first, let preview = Self.previewPNG(of: first) {
                    item.imageWidth = preview.width
                    item.imageHeight = preview.height
                    // The stored copy keeps the thumbnail alive if the original is moved or
                    // deleted — only kept when the user wants image copies on disk.
                    if settings.clipboardKeepImages { item.imageFile = ClipboardStore.shared.saveImage(preview.data) }
                }
            } else {
                item.kind = .file
            }
            ClipboardStore.shared.add(item)
            return
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            capture(text: string, into: item)
            return
        }

        if settings.clipboardKeepImages, types.contains(.png) || types.contains(.tiff),
           let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            item.kind = .image
            item.imageDigest = ClipboardStore.digest(of: png)
            item.imageWidth = rep.pixelsWide
            item.imageHeight = rep.pixelsHigh
            // Same picture again: reuse the stored file rather than writing a second copy.
            if let existing = ClipboardStore.shared.items.first(where: { $0.imageDigest == item.imageDigest }) {
                item.imageFile = existing.imageFile
            } else {
                item.imageFile = ClipboardStore.shared.saveImage(png)
            }
            guard item.imageFile != nil else { return }
            ClipboardStore.shared.add(item)
        }
    }

    private func capture(text original: String, into base: ClipboardItem) {
        var item = base
        let text = String(original.prefix(100_000))
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)

        if let color = ColorTools.parse(trimmed) {
            item.kind = .color
            item.text = trimmed
            item.colorHex = ColorTools.hex(color)
            ClipboardStore.shared.add(item)
            return
        }

        item.kind = Self.isLink(trimmed) ? .link : (Self.looksLikeCode(text) ? .code : .text)

        item.text = text
        ClipboardStore.shared.add(item)
    }

    // MARK: - Classification

    private static func isImageFile(_ url: URL) -> Bool {
        UTType(filenameExtension: url.pathExtension)?.conforms(to: .image) == true
    }

    /// A downscaled PNG copy of an image file, so its thumbnail survives the original being
    /// moved or deleted.
    private static func previewPNG(of url: URL) -> (data: Data, width: Int, height: Int)? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
        let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any]
        let width = properties?[kCGImagePropertyPixelWidth] as? Int ?? 0
        let height = properties?[kCGImagePropertyPixelHeight] as? Int ?? 0
        guard let cg = CGImageSourceCreateThumbnailAtIndex(source, 0, [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 1_024,
        ] as CFDictionary) else { return nil }
        guard let png = NSBitmapImageRep(cgImage: cg).representation(using: .png, properties: [:]) else { return nil }
        return (png, width, height)
    }

    static func isLink(_ string: String) -> Bool {
        guard !string.contains(where: \.isWhitespace), string.count < 2_048 else { return false }
        if string.lowercased().hasPrefix("www."), string.contains(".") { return true }
        guard let url = URL(string: string), let scheme = url.scheme?.lowercased() else { return false }
        switch scheme {
        case "http", "https", "ftp", "ftps", "ssh", "git": return url.host != nil
        case "mailto", "tel": return true
        default: return false
        }
    }

    /// A deliberately cheap heuristic: count independent signals and call it code at two.
    /// A wrong guess only misfiles a row under "Kod" instead of "Tekst" — nothing breaks.
    static func looksLikeCode(_ text: String) -> Bool {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: true)
        var score = 0

        // A shell command: starts with a well-known tool name and carries flags or operators.
        let firstLine = String(lines.first ?? "").trimmingCharacters(in: .whitespaces)
        let shellTools = ["ls", "cd", "git", "npm", "npx", "pnpm", "yarn", "brew", "sudo", "curl", "wget",
                          "pip", "pip3", "python", "python3", "node", "make", "swift", "docker", "kubectl",
                          "cat", "grep", "chmod", "mkdir", "rm", "cp", "mv", "ssh", "open", "defaults"]
        let firstWord = firstLine.drop { $0 == "$" || $0 == " " }.prefix { !$0.isWhitespace }
        if shellTools.contains(String(firstWord)),
           firstLine.contains(" -") || firstLine.contains("&&") || firstLine.contains("|") || firstLine.contains(" /") {
            score += 2
        }

        let keywords = [
            "func ", "def ", "class ", "import ", "const ", "let ", "var ", "return ", "#include",
            "function ", "SELECT ", "FROM ", "public ", "private ", "struct ", "enum ", "=> ", "-> ",
            "</", "/>", "<?php", "#!/", "$ ", "sudo ", "git ", "npm ", "pip ", "brew ",
            "on run", "tell application", "end tell",
        ]
        if keywords.contains(where: { text.contains($0) }) { score += 1 }

        let symbols: [Character] = ["{", "}", ";", "(", ")", "[", "]", "=", "<", ">"]
        let symbolCount = text.filter { symbols.contains($0) }.count
        if Double(symbolCount) / Double(max(text.count, 1)) > 0.04 { score += 1 }

        if lines.count > 1 {
            let indented = lines.filter { $0.hasPrefix("    ") || $0.hasPrefix("\t") || $0.hasPrefix("  ") }
            if indented.count * 3 >= lines.count { score += 1 }
        }
        if text.contains("{") && text.contains("}") && text.contains(";") { score += 1 }
        if lines.contains(where: { $0.hasPrefix("//") || $0.hasPrefix("# ") || $0.hasPrefix("/*") || $0.hasPrefix("--") }) {
            score += lines.count > 1 ? 1 : 0
        }
        return score >= 2
    }
}
